FROM ubuntu:focal-20200423 AS add-apt-repositories

#RUN apt-get update \
# && DEBIAN_FRONTEND=noninteractive apt-get install -y gnupg \
# && apt-key adv --fetch-keys http://www.webmin.com/jcameron-key.asc \
# && echo "deb http://download.webmin.com/download/repository sarge contrib" >> /etc/apt/sources.list

CMD ["/bin/bash"]
